#!/usr/bin/env node
// Copyright 2017 Google Inc. All Rights Reserved.
// Modifications Copyright 2018 Minsuk Kahng.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =============================================================================

const path = require('path');
const spawn = require('cross-spawn');
const shell = require('shelljs');

const tsPath = path.join('demo', 'ganlab.ts');
const outputPath = path.join('output', 'bundle.js');

const cmd = path.join('node_modules', '.bin', 'browserify');
const child = spawn(cmd,
    [tsPath, '-p', '[tsify', '-p', '../lib/tsconfig.json]', '-o' , outputPath],
    {detached: false});
child.stdout.pipe(process.stdout);
child.stderr.pipe(process.stderr);
child.on('close', () => console.log(`Stored bundle in ${outputPath}`));
